# Test variables
image:
  - Visual Studio 2013
  - Ubuntu

# Build architecture
platform:
  - x64

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# branches to build
branches:
  # whitelist
  only:
    - master

for:

  -
    matrix:
      only:
        - image: Visual Studio 2013
      

    build_script:
      - ECHO %APPVEYOR_URL%

  - 
    matrix:
      only:
        - image: Ubuntu

    build_script:
      - echo $APPVEYOR_URL
