# Build worker image (VM template)
image:
  - ubuntu

platform:
  - x64

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# branches to build
branches:
  # whitelist
  only:
    - master

install:
  - sudo apt update
  - sudo apt install build-essential qt5-default qttools5-dev-tools libqt5webkit5-dev libqt5script5 qtscript5-dev -y

build_script:
  - qmake Libki.pro
  - make
  - mkdir -p deploy/linux/deb/usr/bin
  - mkdir -p deploy/linux/deb/etc/xdg
  - cp libkiclient deploy/linux/deb/usr/bin/libkiclient
  - cp example.ini deploy/linux/deb/etc/xdg/Libki.ini
  - cd deploy/linux
  - sed -i 's/VERSION/latest/g' DEBIAN/control
  - dpkg -b deb Libki_Client_Installer.deb

# defines what we can export from the build environment
artifacts:
  - path: 'deploy\linux\Libki_Client_Installer.deb'
    name: 'Libki Client (Unstable) [$(APPVEYOR_REPO_COMMIT)]'

# deployment configuration, deploy to github releases
deploy:
  release: libki-client-unstable-v$(APPVEYOR_REPO_COMMIT)
  description: 'Libki Client (Unstable) [$(APPVEYOR_REPO_COMMIT)]'
  artifact: 'deploy/linux/Libki_Client_Installer.deb'
  provider: GitHub
  auth_token:
    secure: jERqDlxrRwuTdyrZqwGa9/Yku9WdvPtzDMT4DuNq/M8SQFUSi1aLK6uGekJ3YSEK
  draft: false
  prerelease: true
  force_update: true
  skip_tags: true                  # Build only for branches not tags
  on:
    branch: master                 # release from master branch only
