# Test variables
image:
  - Visual Studio 2013
  - Ubuntu

# Build architecture
platform:
  - x64

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# branches to build
branches:
  # whitelist
  only:
    - master

for:

  -
    matrix:
      only:
        - image: Visual Studio 2013
      

    build_script:
      - ps: $fvstring = gci libki.rc | Select-String "FileVersion" -CaseSensitive
      - ps: $fvstring -match '[0-9]+\.[0-9]+\.[0-9]+' >$null
      - ps: $vers = $matches.values
      - ps: Write-Host $vers

  - 
    matrix:
      only:
        - image: Ubuntu

    build_script:
      - echo $APPVEYOR_URL
