# Build worker image (VM template)
image:
  - Visual Studio 2013
  - Ubuntu

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# branches to build
branches:
  # whitelist
  only:
    - master

for:

  -
    matrix:
      only:
        - image: Visual Studio 2013

    platform:
      - x86
      
    # scripts that run after cloning repository
    install:
      - ps: Write-Host $env:PLATFORM

  - 
    matrix:
      only:
        - image: Ubuntu

    platform:
      - x64

    install:
      - echo $PLATFORM
